[tool.poetry]
name = "ecqm-dedupe"
version = "0.1.0"
description = ""
authors = ["Pat Sier <patrick.sier@cms.hhs.gov>"]

[tool.poetry.dependencies]
python = "^3.10"
dedupe = "^2.0.19"
Flask = "^2.2.2"
splink = "^3.9.9"
click = "^8.1.7"
altair = "^5.1.2"
pandas = "^2.1.3"
faker = "^20.1.0"

[tool.poetry.dev-dependencies]
black = "^22.10.0"
flake8 = "^5.0.4"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
