[tool.poetry]
name = "cli"
version = "0.1.0"
description = ""
authors = ["Pat Sier <patrick.sier@cms.hhs.gov>",
    "Isaac Milarsky <imilarsky@gmail.com>" ]

[tool.poetry.dependencies]
python = "^3.10"
splink = "^3.9.9"
click = "^8.1.7"
pandas = "^2.1.3"
faker = "^20.1.0"
pytest = "^7.4.3"
openpyxl = "^3.1.2"
lxml = "^5.2.2"
pyarrow = "^16.1.0"
python-dateutil = "^2.9.0.post0"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true